_wandb:
  code_path: code/volumetric_approach/hp_search_voldata.py
batch_size: 4
channels:
- 1
- 16
- 32
- 64
- 32
channels1: 1
channels2: 16
channels3: 32
channels4: 64
channels5: 32
dropout: 0.5
epochs: 60
input_dims: !!python/tuple
- 91
- 109
- 91
kernel_size:
- 5
- 5
- 5
- 5
last_cnn_dims:
- 5
- 6
- 5
learning_rate: 1.0e-05
lin_neurons:
- 256
- 64
lin_neurons1: 256
lin_neurons2: 64
n_classes: 5
pooling_kernel: 2
train_fn: !!python/name:delphi.utils.train_fns.standard_train ''
