_wandb:
  code_path: code/05_volumetric_approach/hp_search_voldata.py
batch_size: 32
channels:
- 1
- 16
- 8
- 64
- 64
channels1: 1
channels2: 16
channels3: 8
channels4: 64
channels5: 64
dropout: 0.3
epochs: 60
input_dims: !!python/tuple
- 91
- 109
- 91
kernel_size:
- 5
- 5
- 5
- 5
last_cnn_dims:
- 5
- 6
- 5
learning_rate: 0.001
lin_neurons:
- 256
- 64
lin_neurons1: 256
lin_neurons2: 64
n_classes: 5
pooling_kernel: 2
train_fn: !!python/name:delphi.utils.train_fns.standard_train ''
