_wandb:
  code_path: code/volumetric_approach/hp_search_voldata.py
batch_size: 32
channels:
- 1
- 8
- 32
- 16
- 128
channels1: 1
channels2: 8
channels3: 32
channels4: 16
channels5: 128
dropout: 0.3
epochs: 60
input_dims: !!python/tuple
- 91
- 109
- 91
kernel_size:
- 7
- 7
- 7
- 7
last_cnn_dims:
- 5
- 6
- 5
learning_rate: 1.0e-05
lin_neurons:
- 256
- 128
lin_neurons1: 256
lin_neurons2: 128
n_classes: 5
pooling_kernel: 2
train_fn: !!python/name:delphi.utils.train_fns.standard_train ''
