program: hp_search_voldata.py
entity: philis893
name: volume-exploration-sweep
project: thesis
method: random
metric:
  name: valid_acc
parameters:
  channels1:
    value: 1
  channels2:
    values: [8, 16]
  channels3:
    values: [8, 16, 32]
  channels4:
    values: [16, 32, 64]
  channels5:
    values: [32, 64, 128]
  kernel_size:
    values: [3, 5, 7]
  lin_neurons1:
    values: [256, 128]
  lin_neurons2:
    values: [256, 128, 64]
  batch_size:
    values: [4, 8, 16, 32]
  dropout:
    values: [.3, .4, .5, .6, .7]
  learning_rate:
    values: [0.00001, 0.0001, 0.001]
  epochs:
    value: 60