_wandb:
  code_path: code/05_volumetric_approach/hp_search_voldata.py
batch_size: 16
channels:
- 1
- 16
- 16
- 64
- 128
channels1: 1
channels2: 16
channels3: 16
channels4: 64
channels5: 128
dropout: 0.6
epochs: 60
input_dims: !!python/tuple
- 91
- 109
- 91
kernel_size:
- 5
- 5
- 5
- 5
last_cnn_dims:
- 5
- 6
- 5
learning_rate: 0.0001
lin_neurons:
- 128
- 64
lin_neurons1: 128
lin_neurons2: 64
n_classes: 5
pooling_kernel: 2
train_fn: !!python/name:delphi.utils.train_fns.standard_train ''
